"""
MSR Fuel Channel Radiative Heat Transfer Case Study
====================================================
Solves the 1D steady-state radial energy equation in a cylindrical
molten salt fuel channel with volumetric fission heat generation.

Physics:
    The governing equation in cylindrical coordinates is:

        (1/r) d/dr [ r k_eff(T) dT/dr ] + q''' = 0

    where:
        k_eff(T) = k_phonon(T) + k_rad(T)
        k_phonon(T) = k_ref * (T_fus / T)^0.4    (Gheribi model)
        k_rad(T) = 16 n^2 sigma T^3 / (3 kappa_P) (Rosseland diffusion)

    The Rosseland approximation is valid here because at the reactor
    channel scale (R ~ 5 cm), the optical thickness tau = kappa_P * R
    is typically >> 1 for molten salts (tau ~ 50-5000).

    Boundary conditions:
        r = 0:  dT/dr = 0   (centerline symmetry)
        r = R:  T = T_wall   (prescribed wall temperature)

    The comparison between conduction-only and conduction+radiation
    profiles shows:
        1. How much radiation reduces the peak centerline temperature
        2. The radial distribution of radiative heat transfer fraction
        3. The practical significance for MSR safety margins

Case Studies:
    Case 1 — Temperature profile comparison (conduction vs conduction+radiation)
    Case 2 — Radiative fraction across the channel radius

References:
    Gheribi et al. (2014) Sol. Energy Mater. Sol. Cells 126, 11-25.
    Chaleff et al. (2016) Nucl. Technol. 196(3), 1-9.
    Robertson et al. (2022) Appl. Phys. Lett. 131(22), 225102.
    Siegel & Howell (2002) Thermal Radiation Heat Transfer, 4th ed.

Dependencies:
    Requires 'Salt_RHT_Properties.csv' generated by the absorption model.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.integrate import solve_bvp
from scipy.interpolate import interp1d
from scipy.constants import Stefan_Boltzmann as sigma_SB
import os


# =============================================================================
# 0. PLOT FORMATTING
# =============================================================================
plt.rcParams.update({
    "font.family":          "serif",
    "font.serif":           ["Times New Roman"],
    "mathtext.fontset":     "cm",
    "axes.labelsize":       11,
    "xtick.labelsize":      10,
    "ytick.labelsize":      10,
    "legend.fontsize":       9,
    "axes.spines.top":      True,
    "axes.spines.right":    True,
    "xtick.direction":      "in",
    "ytick.direction":      "in",
    "xtick.minor.visible":  True,
    "ytick.minor.visible":  True,
})


# =============================================================================
# 1. REACTOR & SALT CONFIGURATION
# =============================================================================

# Reactor channel parameters (Mk1 PB-FHR representative values)
REACTOR_CONFIGS = {
    'FLiNaK': {
        'R_channel': 0.05,          # Channel radius [m] (5 cm)
        'q_vol': 2.5e7,             # Volumetric heat generation [W/m^3]
        'T_wall': 900.0,            # Wall temperature [K]
        'k_phonon_ref': 0.60,       # Phonon k at T_fus [W/m/K]
        'T_fus': 727.0,             # Melting temperature [K]
        'k_phonon_exp': 0.4,        # Gheribi exponent
    },
    'FLiBe': {
        'R_channel': 0.05,
        'q_vol': 2.5e7,
        'T_wall': 900.0,
        'k_phonon_ref': 1.0,
        'T_fus': 732.0,
        'k_phonon_exp': 0.4,
    },
    'NaCl': {
        'R_channel': 0.05,
        'q_vol': 1.0e7,             # Lower for chloride fast reactor
        'T_wall': 1100.0,
        'k_phonon_ref': 0.50,
        'T_fus': 1073.8,
        'k_phonon_exp': 0.4,
    },
}


def k_phonon(T, cfg):
    """Phonon thermal conductivity: k_ref * (T_fus/T)^exp [W/m/K]."""
    T_safe = np.clip(T, 1.0, None)
    return cfg['k_phonon_ref'] * (cfg['T_fus'] / T_safe) ** cfg['k_phonon_exp']


# =============================================================================
# 2. DATA LOADING
# =============================================================================

def load_optical_properties(salt_name, csv_path='Salt_RHT_Properties.csv'):
    """
    Load kappa_P(T) and n(T) from the absorption model CSV and return
    interpolation functions that the ODE solver can call at any T.

    Returns
    -------
    kappa_interp : callable(T) -> kappa_P [m^-1]
    n_interp     : callable(T) -> n (refractive index)
    """
    try:
        script_dir = os.path.dirname(os.path.abspath(__file__))
    except NameError:
        script_dir = os.getcwd()
    full_path = os.path.join(script_dir, csv_path)

    if not os.path.exists(full_path):
        raise FileNotFoundError(f"CSV not found: {full_path}")

    df = pd.read_csv(full_path)
    row = df[df['Salt'] == salt_name]
    if row.empty:
        available = df['Salt'].unique().tolist()
        raise ValueError(
            f"Salt '{salt_name}' not found. Available: {available}")

    row = row.iloc[0]
    T_arr = np.array([float(x) for x in
                      str(row['Temperature_List_K']).split(',')])
    kappa_arr = np.array([float(x) for x in
                          str(row['Absorption_List_m1']).split(',')])
    n_arr = np.array([float(x) for x in
                      str(row['Refractive_Index_List']).split(',')])

    # Cubic interpolation for smooth ODE integration
    kappa_interp = interp1d(T_arr, kappa_arr, kind='cubic',
                            fill_value='extrapolate')
    n_interp = interp1d(T_arr, n_arr, kind='linear',
                        fill_value='extrapolate')

    return kappa_interp, n_interp


# =============================================================================
# 3. ODE SYSTEM
# =============================================================================

def build_ode_system(cfg, kappa_interp, n_interp, include_radiation=True):
    """
    Construct the BVP system for scipy.integrate.solve_bvp.

    Variables:
        y[0] = T       (temperature)
        y[1] = dT/dr   (temperature gradient)

    The energy equation:
        d/dr[r k_eff dT/dr] + r q''' = 0

    expanded gives:
        T'' = -q'''/k_eff - (1/r)T' - (dk_eff/dT)(T')^2 / k_eff

    At r = 0, L'Hopital's rule gives:
        2 T'' = -q'''/k_eff   (since T' = 0 by symmetry)
    """
    q_vol = cfg['q_vol']
    R = cfg['R_channel']

    def k_rad(T):
        """Rosseland radiative conductivity [W/m/K]."""
        if not include_radiation:
            return np.zeros_like(T)
        kappa = np.clip(kappa_interp(T), 1.0, None)
        n = np.clip(n_interp(T), 0.5, 3.0)
        return (16.0 * n**2 * sigma_SB * T**3) / (3.0 * kappa)

    def k_eff(T):
        return k_phonon(T, cfg) + k_rad(T)

    def dk_eff_dT(T):
        """Numerical derivative of k_eff w.r.t. T."""
        dT = 0.5
        return (k_eff(T + dT) - k_eff(T - dT)) / (2.0 * dT)

    def ode(r, y):
        T = y[0]
        dTdr = y[1]

        k_val = k_eff(T)
        dk_val = dk_eff_dT(T)

        d2Tdr2 = np.zeros_like(T)
        for i in range(len(r)):
            if r[i] < 1e-8:
                # L'Hopital at centerline: 2*T'' = -q'''/k_eff
                d2Tdr2[i] = -(q_vol / k_val[i]) / 2.0
            else:
                d2Tdr2[i] = (-(q_vol / k_val[i])
                             - (dTdr[i] / r[i])
                             - (dk_val[i] / k_val[i]) * dTdr[i]**2)

        return np.vstack((dTdr, d2Tdr2))

    def bc(ya, yb):
        """BC: dT/dr=0 at r=0, T=T_wall at r=R."""
        return np.array([ya[1], yb[0] - cfg['T_wall']])

    return ode, bc, k_eff


# =============================================================================
# 4. SOLVER
# =============================================================================

def solve_channel(cfg, kappa_interp, n_interp, include_radiation=True,
                  n_mesh=100):
    """
    Solve the radial temperature profile using solve_bvp.

    Returns (r_fine, T_fine, k_eff_func) on a 300-point grid.
    """
    R = cfg['R_channel']
    r_mesh = np.linspace(0, R, n_mesh)

    # Initial guess: parabolic profile
    k_ref = cfg['k_phonon_ref']
    T_guess = cfg['T_wall'] + (cfg['q_vol'] / (4 * k_ref)) * (R**2 - r_mesh**2)
    y_guess = np.vstack((T_guess, np.zeros_like(r_mesh)))

    ode, bc, k_eff = build_ode_system(
        cfg, kappa_interp, n_interp, include_radiation)

    sol = solve_bvp(ode, bc, r_mesh, y_guess, max_nodes=5000, tol=1e-6)

    if not sol.success:
        print(f"  Warning: solver {'converged' if sol.success else 'did NOT converge'}")

    r_fine = np.linspace(0, R, 300)
    T_fine = sol.sol(r_fine)[0]

    return r_fine, T_fine, k_eff


# =============================================================================
# 5. PLOTTING
# =============================================================================

def plot_case_study(salt_name, cfg, kappa_interp, n_interp, output_dir):
    """
    Generate the two-panel case study figure:
        Left:  Temperature profiles (conduction-only vs with radiation)
        Right: Radiative fraction across the channel radius
    """
    print(f"  Solving conduction-only baseline...")
    r_cond, T_cond, _ = solve_channel(
        cfg, kappa_interp, n_interp, include_radiation=False)

    print(f"  Solving with internal thermal radiation...")
    r_rad, T_rad, k_eff_func = solve_channel(
        cfg, kappa_interp, n_interp, include_radiation=True)

    R_cm = cfg['R_channel'] * 100  # Convert to cm for plotting

    # ---- Compute radiative fraction across radius ----
    k_ph_vals = k_phonon(T_rad, cfg)
    k_eff_vals = k_eff_func(T_rad)
    k_rad_vals = k_eff_vals - k_ph_vals
    rad_fraction = np.clip(k_rad_vals / k_eff_vals * 100, 0, 100)

    # ---- Optical thickness for annotation ----
    kappa_center = float(np.clip(kappa_interp(T_rad[0]), 1.0, None))
    tau = kappa_center * cfg['R_channel']

    # Peak temperatures
    T_peak_cond = T_cond[0]
    T_peak_rad = T_rad[0]
    delta_T = T_peak_cond - T_peak_rad

    # ---- Figure ----
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.5),
                                    constrained_layout=True)

    # Panel 1: Temperature profiles
    ax1.plot(r_cond * 100, T_cond, 'k--', linewidth=2,
             label='Conduction only ($k_{\\mathrm{phonon}}$)')
    ax1.plot(r_rad * 100, T_rad, 'r-', linewidth=2,
             label='Conduction + Radiation ($k_{\\mathrm{eff}}$)')

    # Shading for temperature reduction
    ax1.fill_betweenx([min(T_rad.min(), T_cond.min()) - 20,
                        T_peak_cond + 20],
                       0, 0, alpha=0)  # invisible, just for y-limits
    ax1.fill_between(r_rad * 100, T_cond, T_rad,
                     where=(T_cond > T_rad),
                     color='red', alpha=0.08,
                     label=f'$\\Delta T_{{\\mathrm{{peak}}}}$ = '
                           f'{delta_T:.1f} K')

    # Annotations
    ax1.annotate(f'{T_peak_cond:.0f} K',
                 xy=(0.3, T_peak_cond), fontsize=9, color='black',
                 ha='left', va='bottom')
    ax1.annotate(f'{T_peak_rad:.0f} K',
                 xy=(0.3, T_peak_rad), fontsize=9, color='red',
                 ha='left', va='top')

    ax1.set_xlabel('Radial Position, $r$ (cm)')
    ax1.set_ylabel('Temperature (K)')
    ax1.set_title(f'{salt_name} — Fuel Channel Temperature Profile')
    ax1.set_xlim(0, R_cm)
    ax1.legend(loc='lower left', fontsize=8)

    # Info box
    ax1.text(0.97, 0.97,
             f'$R$ = {R_cm:.0f} cm\n'
             f"$q'''$ = {cfg['q_vol']/1e6:.0f} MW/m$^3$\n"
             f'$T_{{\\mathrm{{wall}}}}$ = {cfg["T_wall"]:.0f} K\n'
             f'$\\tau$ = {tau:.0f}',
             transform=ax1.transAxes, fontsize=8,
             va='top', ha='right',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='wheat',
                       alpha=0.7))

    # Panel 2: Radiative fraction
    ax2.plot(r_rad * 100, rad_fraction, 'b-', linewidth=2)
    ax2.fill_between(r_rad * 100, 0, rad_fraction,
                     color='blue', alpha=0.08)

    ax2.set_xlabel('Radial Position, $r$ (cm)')
    ax2.set_ylabel('Radiative Fraction of $k_{\\mathrm{eff}}$ (%)')
    ax2.set_title(f'{salt_name} — Radiative Heat Transfer Contribution')
    ax2.set_xlim(0, R_cm)
    ax2.set_ylim(0, max(rad_fraction.max() * 1.15, 5))

    # Annotate peak and wall values
    ax2.annotate(f'{rad_fraction[0]:.1f}% (center)',
                 xy=(0.3, rad_fraction[0]),
                 fontsize=8, color='blue', ha='left')
    ax2.annotate(f'{rad_fraction[-1]:.1f}% (wall)',
                 xy=(R_cm - 0.3, rad_fraction[-1]),
                 fontsize=8, color='blue', ha='right')

    # Save
    filepath = os.path.join(output_dir,
                            f'MSR_Channel_{salt_name}.pdf')
    fig.savefig(filepath, dpi=300, bbox_inches='tight')
    print(f"  Saved: {filepath}")
    return fig


# =============================================================================
# 6. SUMMARY TABLE
# =============================================================================

def print_summary(salt_name, cfg, kappa_interp, n_interp):
    """Print key metrics for the channel solution."""
    # Solve both cases
    _, T_cond, _ = solve_channel(cfg, kappa_interp, n_interp, False)
    _, T_rad, k_eff_func = solve_channel(cfg, kappa_interp, n_interp, True)

    k_ph_center = k_phonon(T_rad[0], cfg)
    k_eff_center = k_eff_func(T_rad[0])
    k_rad_center = k_eff_center - k_ph_center
    frac = k_rad_center / k_eff_center * 100

    kappa_center = float(kappa_interp(T_rad[0]))
    tau = kappa_center * cfg['R_channel']

    print(f"\n  {'='*50}")
    print(f"  {salt_name} MSR Channel Summary")
    print(f"  {'='*50}")
    print(f"  Channel radius:          {cfg['R_channel']*100:.0f} cm")
    print(f"  Heat generation:         {cfg['q_vol']/1e6:.0f} MW/m^3")
    print(f"  Wall temperature:        {cfg['T_wall']:.0f} K")
    print(f"  {'─'*50}")
    print(f"  Peak T (conduction):     {T_cond[0]:.1f} K")
    print(f"  Peak T (cond+rad):       {T_rad[0]:.1f} K")
    print(f"  Temperature reduction:   {T_cond[0]-T_rad[0]:.1f} K")
    print(f"  {'─'*50}")
    print(f"  k_phonon (center):       {k_ph_center:.3f} W/m/K")
    print(f"  k_rad (center):          {k_rad_center:.3f} W/m/K")
    print(f"  k_eff (center):          {k_eff_center:.3f} W/m/K")
    print(f"  Radiative fraction:      {frac:.1f}%")
    print(f"  {'─'*50}")
    print(f"  kappa_P (center):        {kappa_center:.0f} m^-1")
    print(f"  Optical thickness tau:   {tau:.0f}")
    print(f"  {'='*50}\n")


# =============================================================================
# 7. MAIN
# =============================================================================

if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    figs_dir = os.path.join(script_dir, 'Figures')
    os.makedirs(figs_dir, exist_ok=True)

    # ---- Select salts to analyze ----
    SALTS_TO_ANALYZE = ['FLiNaK']

    for salt_name in SALTS_TO_ANALYZE:
        print(f"\n{'='*60}")
        print(f"  MSR Channel Case Study: {salt_name}")
        print(f"{'='*60}")

        if salt_name not in REACTOR_CONFIGS:
            print(f"  No reactor config for {salt_name}. Skipping.")
            continue

        cfg = REACTOR_CONFIGS[salt_name]

        try:
            kappa_interp, n_interp = load_optical_properties(salt_name)
        except (FileNotFoundError, ValueError) as e:
            print(f"  Error: {e}")
            continue

        print_summary(salt_name, cfg, kappa_interp, n_interp)

        plot_case_study(salt_name, cfg, kappa_interp, n_interp, figs_dir)

    plt.show()
    print("Done. Figures saved to ./Figures/")
