"""
LFA Radiative Thermal Conductivity Case Studies
================================================
Demonstrates how the predicted absorption coefficient and refractive index
affect the interpretation of LFA thermal conductivity measurements.

Physics:
    An LFA measurement yields an apparent thermal diffusivity alpha_app,
    which is converted to thermal conductivity via:

        k_measured = alpha_app * rho(T) * cp(T)

    If the salt is semi-transparent, the measured k includes BOTH phonon
    conduction and radiative transport:

        k_measured = k_phonon + k_rad

    where the Deissler bridging approximation gives:

        k_rad = 16 n^2 sigma T^3 / (3 kappa_P + 4/L)

    This reduces to the Rosseland diffusion limit when tau = kappa_P * L >> 1
    and to the optically-thin gap radiation when tau << 1.

    An LFA experiment that doesn't account for radiation attributes ALL
    of k_measured to phonon conduction, overestimating k_phonon.

Case Studies:
    Case 1 — Thermal conductivity decomposition: k_phonon vs k_rad vs k_total
             with published LFA data overlay for comparison.
    Case 2 — Sensitivity of k_total to LFA sample thickness (1, 2, 3 mm),
             showing how thinner samples see more radiative contribution.

References:
    Parker et al. (1961) J. Appl. Phys. 32(9), 1679-1684.
    Dong et al. (2024) Prog. Nat. Sci. Mater. Int. 34, 345-353.
    Robertson et al. (2022) Appl. Phys. Lett. 131(22), 225102.
    Gheribi et al. (2014) Sol. Energy Mater. Sol. Cells 126, 11-25.
    Deissler (1964) J. Heat Transfer 86(2), 240-246.

Dependencies:
    Requires 'Salt_RHT_Properties.csv' generated by the absorption model.
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.constants import Stefan_Boltzmann as sigma_SB
import os
from typing import Dict, List, Tuple, Optional


# =============================================================================
# 0. PLOT FORMATTING
# =============================================================================
plt.rcParams.update({
    "font.family":          "serif",
    "font.serif":           ["Times New Roman"],
    "mathtext.fontset":     "cm",
    "axes.labelsize":       11,
    "xtick.labelsize":      10,
    "ytick.labelsize":      10,
    "legend.fontsize":       8,
    "axes.spines.top":      True,
    "axes.spines.right":    True,
    "xtick.direction":      "in",
    "ytick.direction":      "in",
    "xtick.minor.visible":  True,
    "ytick.minor.visible":  True,
})


# =============================================================================
# 1. SALT THERMOPHYSICAL PROPERTIES
# =============================================================================
# Each salt needs: density rho(T), specific heat cp(T), and a reference
# phonon thermal conductivity.
#
# Format:
#   'rho': (a, b) for rho = a + b*T  [kg/m^3, K]      — from MSTDB
#   'cp':  float or (a, b) for cp = a + b*T  [J/kg/K]  — from literature
#   'T_fus': melting temperature [K]
#   'k_phonon_ref': reference phonon conductivity near T_fus [W/m/K]
#   'k_phonon_exp': exponent for T-dependence: k_ph = k_ref*(T_fus/T)^exp
#       Gheribi et al. (2014) suggest exp ~ 0.3-0.5 for molten salts
#   'L_lfa': default LFA sample thickness [m]
#
#   'published_k': list of dicts with published LFA/measurement data
#       Each dict: {'T_K': [...], 'k': [...], 'label': '...', 'marker': '...'}

SALT_CASES: Dict[str, dict] = {
    'FLiNaK': {
        'rho': (2680.0, -0.685),        # MSTDB
        'cp': 1880.0,                    # ~constant, Grimes (1966)
        'T_fus': 727.0,
        'k_phonon_ref': 0.60,           # W/m/K — baseline from Khokhlov
        'k_phonon_exp': 0.4,            # Gheribi model exponent
        'L_lfa': 0.002,                  # 2 mm default
        'published_k': [
            # Add your own published LFA data here:
            # {
            #     'T_K': [773, 823, 873, 923, 973],
            #     'k': [0.77, 0.74, 0.72, 0.70, 0.68],
            #     'label': 'Rudenko (2022, LFA)',
            #     'marker': 's', 'color': 'blue',
            # },
        ],
    },
    'NaCl': {
        'rho': (2140.0, -0.543),
        'cp': 1080.0,
        'T_fus': 1073.8,
        'k_phonon_ref': 0.50,
        'k_phonon_exp': 0.4,
        'L_lfa': 0.002,
        'published_k': [],
    },
    'LiF': {
        'rho': (2370.0, -0.50),
        'cp': 2390.0,                    # Janz (1988)
        'T_fus': 1121.2,
        'k_phonon_ref': 1.0,
        'k_phonon_exp': 0.4,
        'L_lfa': 0.002,
        'published_k': [],
    },
}


# =============================================================================
# 2. HELPER FUNCTIONS
# =============================================================================

def load_salt_data(salt_name: str,
                   filename: str = 'Salt_RHT_Properties.csv'
                   ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Load temperature-dependent kappa_P and n_eff from the absorption model CSV.

    Returns
    -------
    T_array     : temperature array [K]
    kappa_array : Planck-mean absorption coefficient [m^-1]
    n_array     : Planck-mean refractive index
    """
    try:
        script_dir = os.path.dirname(os.path.abspath(__file__))
    except NameError:
        script_dir = os.getcwd()
    full_path = os.path.join(script_dir, filename)

    if not os.path.exists(full_path):
        raise FileNotFoundError(
            f"Database not found: {full_path}\n"
            "Run the absorption model first to generate Salt_RHT_Properties.csv.")

    df = pd.read_csv(full_path)
    row = df[df['Salt'] == salt_name]
    if row.empty:
        available = df['Salt'].unique().tolist()
        raise ValueError(
            f"Salt '{salt_name}' not in database. Available: {available}")

    row = row.iloc[0]
    T = np.array([float(x) for x in str(row['Temperature_List_K']).split(',')])
    kappa = np.array([float(x) for x in str(row['Absorption_List_m1']).split(',')])
    n = np.array([float(x) for x in str(row['Refractive_Index_List']).split(',')])

    return T, kappa, n


def density_at_T(rho_coeffs: Tuple[float, float], T: float) -> float:
    """Linear density: rho(T) = a + b*T [kg/m^3]."""
    return rho_coeffs[0] + rho_coeffs[1] * T


def cp_at_T(cp_input, T: float) -> float:
    """Specific heat: constant or linear cp(T) = a + b*T [J/kg/K]."""
    if isinstance(cp_input, (int, float)):
        return float(cp_input)
    return cp_input[0] + cp_input[1] * T


def k_phonon(T: float, T_fus: float, k_ref: float, exponent: float) -> float:
    """
    Phonon thermal conductivity (Gheribi et al., 2014):
        k_phonon(T) = k_ref * (T_fus / T)^exponent

    Gives decreasing k with temperature — expected for phonon conduction
    in liquids where increased thermal motion disrupts heat transfer.
    """
    if T <= 0:
        return k_ref
    return k_ref * (T_fus / T) ** exponent


def k_rad_deissler(T: float, n: float, kappa_P: float, L: float) -> float:
    """
    Deissler bridging radiative conductivity [W/m/K]:

        k_rad = 16 n^2 sigma T^3 / (3 kappa_P + 4/L)

    Smoothly interpolates between:
        - Optically thick (tau >> 1): reduces to Rosseland
        - Optically thin  (tau << 1): radiation across gap ~ L

    Parameters
    ----------
    T       : temperature [K]
    n       : refractive index
    kappa_P : Planck-mean absorption coefficient [m^-1]
    L       : characteristic length (sample thickness) [m]
    """
    if kappa_P <= 0 and L <= 0:
        return 0.0
    denom = 3.0 * kappa_P + (4.0 / L if L > 0 else 0.0)
    if denom <= 0:
        return 0.0
    return 16.0 * n**2 * sigma_SB * T**3 / denom


def k_rad_rosseland(T: float, n: float, kappa_P: float) -> float:
    """
    Rosseland (optically thick) radiative conductivity [W/m/K]:

        k_rad = 16 n^2 sigma T^3 / (3 kappa_P)

    Valid only when optical thickness tau = kappa_P * L >> 1.
    """
    if kappa_P <= 0:
        return 0.0
    return 16.0 * n**2 * sigma_SB * T**3 / (3.0 * kappa_P)


# =============================================================================
# 3. CASE STUDY 1 — Thermal Conductivity Decomposition
# =============================================================================

def case_1_conductivity_decomposition(
        T_array: np.ndarray,
        kappa_array: np.ndarray,
        n_array: np.ndarray,
        salt_name: str,
        salt_props: dict,
        L_lfa: Optional[float] = None,
        output_dir: Optional[str] = None):
    """
    Decompose the measured LFA thermal conductivity into phonon + radiative.

    What this shows:
        A standard LFA measures k_total = k_phonon + k_rad.
        If radiation is not accounted for, all of k_total is attributed
        to phonon conduction — overestimating k_phonon.

        This plot shows:
        - k_phonon(T) alone (what conduction really is)
        - k_rad(T) from the absorption model (what radiation adds)
        - k_total(T) = k_phonon + k_rad (what LFA reports)
        - Published LFA data for comparison

    The gap between k_phonon and k_total IS the radiative error.
    """
    if L_lfa is None:
        L_lfa = salt_props.get('L_lfa', 0.002)
    if output_dir is None:
        try:
            script_dir = os.path.dirname(os.path.abspath(__file__))
        except NameError:
            script_dir = os.getcwd()
        output_dir = os.path.join(script_dir, 'Figures')
    os.makedirs(output_dir, exist_ok=True)

    T_fus = salt_props['T_fus']
    k_ref = salt_props['k_phonon_ref']
    k_exp = salt_props['k_phonon_exp']

    # Only use temperatures above melting
    mask = T_array >= T_fus
    T = T_array[mask]
    kappa = kappa_array[mask]
    n_eff = n_array[mask]

    if len(T) < 2:
        print(f"  Warning: fewer than 2 temperatures above T_fus for {salt_name}")
        return None

    # Compute components
    k_ph = np.array([k_phonon(Ti, T_fus, k_ref, k_exp) for Ti in T])
    k_r = np.array([k_rad_deissler(Ti, ni, ki, L_lfa)
                     for Ti, ni, ki in zip(T, n_eff, kappa)])
    k_total = k_ph + k_r

    # Optical thickness at each temperature
    tau = kappa * L_lfa

    # Radiative fraction at highest temperature
    rad_frac_max = k_r[-1] / k_total[-1] * 100 if k_total[-1] > 0 else 0

    # ---- Plot ----
    fig, ax = plt.subplots(figsize=(7, 5), constrained_layout=True)

    # Phonon-only baseline
    ax.plot(T, k_ph, 'b--', linewidth=1.5,
            label='$k_{\\mathrm{phonon}}(T)$ (conduction only)')

    # Radiative component
    ax.plot(T, k_r, 'r:', linewidth=1.5,
            label=f'$k_{{\\mathrm{{rad}}}}(T)$ (Deissler, L={L_lfa*1e3:.0f} mm)')

    # Total = what LFA measures
    ax.plot(T, k_total, 'k-', linewidth=2.0,
            label='$k_{\\mathrm{total}} = k_{\\mathrm{phonon}} + k_{\\mathrm{rad}}$'
                  ' (LFA measures this)')

    # Shade the radiative contribution
    ax.fill_between(T, k_ph, k_total, alpha=0.15, color='red',
                    label='Radiative contribution')

    # Published LFA data
    published = salt_props.get('published_k', [])
    for pub in published:
        T_pub = np.array(pub['T_K'])
        k_pub = np.array(pub['k'])
        ax.scatter(T_pub, k_pub,
                   marker=pub.get('marker', 'o'),
                   color=pub.get('color', 'green'),
                   s=60, edgecolors='black', linewidth=0.5,
                   zorder=5, alpha=0.8,
                   label=pub.get('label', 'Published LFA'))

    # Annotate radiative fraction
    ax.annotate(
        f'Radiative fraction\nat {T[-1]:.0f} K: {rad_frac_max:.1f}%',
        xy=(T[-1], k_total[-1]),
        xytext=(-120, 30), textcoords='offset points',
        fontsize=9,
        arrowprops=dict(arrowstyle='->', color='red', lw=1.2),
        bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow',
                  edgecolor='red', alpha=0.8))

    # Annotate optical thickness range
    ax.text(0.03, 0.03,
            f'$\\tau$ range: {tau[0]:.1f} – {tau[-1]:.1f}\n'
            f'L = {L_lfa*1e3:.0f} mm',
            transform=ax.transAxes, fontsize=8,
            verticalalignment='bottom',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='wheat', alpha=0.6))

    ax.set_xlabel('Temperature (K)')
    ax.set_ylabel('Thermal Conductivity (W/m$\\cdot$K)')
    ax.set_title(f'{salt_name}: LFA Thermal Conductivity Decomposition',
                 fontweight='bold')
    ax.legend(loc='best', fontsize=8, framealpha=0.9)
    ax.set_xlim(T[0], T[-1])
    ax.set_ylim(bottom=0)

    filepath = os.path.join(output_dir, f'Case1_k_decomposition_{salt_name}.pdf')
    fig.savefig(filepath, bbox_inches='tight', dpi=300)
    print(f"  Saved: {filepath}")

    return fig


# =============================================================================
# 4. CASE STUDY 2 — Sensitivity to LFA Sample Thickness
# =============================================================================

def case_2_thickness_sensitivity(
        T_array: np.ndarray,
        kappa_array: np.ndarray,
        n_array: np.ndarray,
        salt_name: str,
        salt_props: dict,
        L_values: Optional[List[float]] = None,
        output_dir: Optional[str] = None):
    """
    Sensitivity of measured k_total to LFA sample thickness.

    Thinner samples have smaller optical thickness tau = kappa * L,
    so the Deissler correction is relatively larger — more radiation
    crosses the sample, inflating the apparent thermal conductivity.

    This directly shows why LFA measurements at different sample
    thicknesses can give different results for semi-transparent salts.
    """
    if L_values is None:
        L_values = [0.001, 0.002, 0.003]   # 1, 2, 3 mm
    if output_dir is None:
        try:
            script_dir = os.path.dirname(os.path.abspath(__file__))
        except NameError:
            script_dir = os.getcwd()
        output_dir = os.path.join(script_dir, 'Figures')
    os.makedirs(output_dir, exist_ok=True)

    T_fus = salt_props['T_fus']
    k_ref = salt_props['k_phonon_ref']
    k_exp = salt_props['k_phonon_exp']

    mask = T_array >= T_fus
    T = T_array[mask]
    kappa = kappa_array[mask]
    n_eff = n_array[mask]

    if len(T) < 2:
        print(f"  Warning: fewer than 2 temperatures above T_fus for {salt_name}")
        return None

    # Phonon baseline
    k_ph = np.array([k_phonon(Ti, T_fus, k_ref, k_exp) for Ti in T])

    # Reference kappa for tau annotation
    idx_mid = len(T) // 2
    kappa_mid = kappa[idx_mid]

    # ---- Plot ----
    fig, ax = plt.subplots(figsize=(7, 5), constrained_layout=True)

    # Phonon-only baseline
    ax.plot(T, k_ph, 'k:', linewidth=2.0,
            label='$k_{\\mathrm{phonon}}$ (conduction only)')

    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']
    styles = ['-', '--', '-.', ':']

    for j, L in enumerate(L_values):
        k_total = np.empty_like(T)
        for i, (Ti, ni, ki) in enumerate(zip(T, n_eff, kappa)):
            k_r = k_rad_deissler(Ti, ni, ki, L)
            k_total[i] = k_ph[i] + k_r

        tau_mid = kappa_mid * L
        label = (f'$k_{{\\mathrm{{total}}}}$, L = {L*1e3:.0f} mm '
                 f'($\\tau_{{\\mathrm{{mid}}}}$ = {tau_mid:.1f})')
        ax.plot(T, k_total,
                color=colors[j % len(colors)],
                linestyle=styles[j % len(styles)],
                linewidth=1.5, label=label)

    # Published data
    published = salt_props.get('published_k', [])
    for pub in published:
        T_pub = np.array(pub['T_K'])
        k_pub = np.array(pub['k'])
        ax.scatter(T_pub, k_pub,
                   marker=pub.get('marker', 'o'),
                   color=pub.get('color', 'green'),
                   s=60, edgecolors='black', linewidth=0.5,
                   zorder=5, alpha=0.8,
                   label=pub.get('label', 'Published LFA'))

    ax.set_xlabel('Temperature (K)')
    ax.set_ylabel('Thermal Conductivity (W/m$\\cdot$K)')
    ax.set_title(f'{salt_name}: Sensitivity to LFA Sample Thickness',
                 fontweight='bold')
    ax.legend(loc='best', fontsize=8, framealpha=0.9)
    ax.set_xlim(T[0], T[-1])
    ax.set_ylim(bottom=0)

    filepath = os.path.join(output_dir,
                            f'Case2_thickness_sensitivity_{salt_name}.pdf')
    fig.savefig(filepath, bbox_inches='tight', dpi=300)
    print(f"  Saved: {filepath}")

    return fig


# =============================================================================
# 5. SUMMARY TABLE
# =============================================================================

def print_summary_table(T_array: np.ndarray,
                        kappa_array: np.ndarray,
                        n_array: np.ndarray,
                        salt_name: str,
                        salt_props: dict,
                        L_lfa: Optional[float] = None):
    """Print a formatted table of key radiative metrics at select temperatures."""
    if L_lfa is None:
        L_lfa = salt_props.get('L_lfa', 0.002)

    T_fus = salt_props['T_fus']
    k_ref = salt_props['k_phonon_ref']
    k_exp = salt_props['k_phonon_exp']

    mask = T_array >= T_fus
    T = T_array[mask]
    kappa = kappa_array[mask]
    n_eff = n_array[mask]

    # Pick ~8 evenly spaced temperatures
    n_pts = min(8, len(T))
    indices = np.linspace(0, len(T) - 1, n_pts, dtype=int)

    print(f"\n{'='*85}")
    print(f"  Radiative Thermal Conductivity Summary: {salt_name}")
    print(f"  LFA sample thickness = {L_lfa*1e3:.1f} mm")
    print(f"{'='*85}")
    print(f"  {'T [K]':>7}  {'kP [m-1]':>10}  {'n_eff':>7}  {'tau':>7}  "
          f"{'k_ph':>7}  {'k_rad':>7}  {'k_tot':>7}  {'rad%':>6}")
    print(f"  {'-'*7}  {'-'*10}  {'-'*7}  {'-'*7}  "
          f"{'-'*7}  {'-'*7}  {'-'*7}  {'-'*6}")

    for idx in indices:
        Ti = T[idx]
        ki = kappa[idx]
        ni = n_eff[idx]

        tau = ki * L_lfa
        k_ph = k_phonon(Ti, T_fus, k_ref, k_exp)
        k_r = k_rad_deissler(Ti, ni, ki, L_lfa)
        k_tot = k_ph + k_r
        rad_pct = k_r / k_tot * 100 if k_tot > 0 else 0

        print(f"  {Ti:>7.0f}  {ki:>10.1f}  {ni:>7.4f}  {tau:>7.2f}  "
              f"{k_ph:>7.3f}  {k_r:>7.4f}  {k_tot:>7.3f}  {rad_pct:>6.1f}")

    print(f"{'='*85}\n")


# =============================================================================
# 6. MAIN — Run Case Studies
# =============================================================================

if __name__ == '__main__':

    # Which salts to analyze (must exist in Salt_RHT_Properties.csv)
    SALTS_TO_ANALYZE = ['FLiNaK', 'NaCl']

    for salt_name in SALTS_TO_ANALYZE:
        print(f"\n{'='*60}")
        print(f"  Case Studies for: {salt_name}")
        print(f"{'='*60}")

        # Check if salt has properties defined
        if salt_name not in SALT_CASES:
            print(f"  Warning: No thermophysical properties defined for "
                  f"'{salt_name}'. Add to SALT_CASES dict. Skipping.")
            continue

        props = SALT_CASES[salt_name]

        # Load absorption model data
        try:
            T_arr, kappa_arr, n_arr = load_salt_data(salt_name)
        except (FileNotFoundError, ValueError) as e:
            print(f"  Error loading data: {e}")
            continue

        # Summary table
        print_summary_table(T_arr, kappa_arr, n_arr, salt_name, props)

        # Case 1: Conductivity decomposition
        print("  Case 1: Thermal conductivity decomposition...")
        case_1_conductivity_decomposition(
            T_arr, kappa_arr, n_arr, salt_name, props)

        # Case 2: Thickness sensitivity
        print("  Case 2: Sample thickness sensitivity...")
        case_2_thickness_sensitivity(
            T_arr, kappa_arr, n_arr, salt_name, props)

    plt.show()
    print("\nDone. All figures saved to Figures/.")
