"""
LFA Radiative Thermal Conductivity Case Studies
================================================
Demonstrates how the predicted absorption coefficient and refractive index
affect the interpretation of LFA thermal conductivity measurements.

Physics:
    An LFA measurement yields an apparent thermal diffusivity alpha_app,
    which is converted to thermal conductivity via:

        k_measured = alpha_app * rho(T) * cp(T)

    If the salt is semi-transparent, the measured k includes BOTH conduction
    conduction and radiative transport:

        k_measured = k_conduction + k_rad

    where the Deissler bridging approximation gives:

        k_rad = 16 n^2 sigma T^3 / (3 kappa_P + 4/L)

    This reduces to the Rosseland diffusion limit when tau = kappa_P * L >> 1
    and to the optically-thin gap radiation when tau << 1.

    An LFA experiment that doesn't account for radiation attributes ALL
    of k_measured to conduction conduction, overestimating k_conduction.

Case Studies:
    Case 1 — Thermal conductivity decomposition: k_conduction vs k_rad vs k_total
             with published LFA data overlay for comparison.
    Case 2 — Sensitivity of k_total to LFA sample thickness (1, 2, 3 mm),
             showing how thinner samples see more radiative contribution.

References:
    Parker et al. (1961) J. Appl. Phys. 32(9), 1679-1684.
    Dong et al. (2024) Prog. Nat. Sci. Mater. Int. 34, 345-353.
    Robertson et al. (2022) Appl. Phys. Lett. 131(22), 225102.
    Gheribi et al. (2014) Sol. Energy Mater. Sol. Cells 126, 11-25.
    Deissler (1964) J. Heat Transfer 86(2), 240-246.

Dependencies:
    Requires 'Salt_RHT_Properties.csv' generated by the absorption model.
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.constants import Stefan_Boltzmann as sigma_SB
import os
from typing import Dict, List, Tuple, Optional

# Import spectral model helpers
from abs_model_claude_V2 import compute_alpha_total, planck_spectral_radiance


def place_legend_avoiding_points(ax, fontsize=9, candidate_locs=None, padding_px=2, first_label: Optional[str] = None):
    """
    Place the legend at the first candidate location that does not overlap
    any plotted data points. Falls back to 'upper right' if all overlap.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
    fontsize : int
    candidate_locs : list of str
    padding_px : int - extra pixel padding around legend bbox to treat as occupied
    """
    if candidate_locs is None:
        candidate_locs = [
            'upper right', 'upper left', 'lower left', 'lower right',
            'center left', 'center right', 'upper center', 'lower center', 'center'
        ]

    fig = ax.figure
    # Ensure renderer exists
    fig.canvas.draw()
    try:
        renderer = fig.canvas.get_renderer()
    except Exception:
        renderer = None

    # Collect screen-space positions of plotted points
    pts = []
    # Lines
    for line in ax.get_lines():
        xdata = np.asarray(line.get_xdata())
        ydata = np.asarray(line.get_ydata())
        if xdata.size and ydata.size:
            for x, y in zip(xdata, ydata):
                pts.append(ax.transData.transform((x, y)))
    # Collections (scatter)
    for coll in ax.collections:
        offsets = getattr(coll, 'get_offsets', lambda: None)()
        if offsets is not None:
            for xy in offsets:
                try:
                    pts.append(ax.transData.transform((xy[0], xy[1])))
                except Exception:
                    continue

    # Prepare handles/labels and optionally reorder so first_label appears first
    handles, labels = ax.get_legend_handles_labels()
    if first_label and first_label in labels:
        idx = labels.index(first_label)
        # move the chosen entry to the front
        handles = [handles[idx]] + handles[:idx] + handles[idx+1:]
        labels  = [labels[idx]]  + labels[:idx]  + labels[idx+1:]

    # Try candidate locations
    for loc in candidate_locs:
        # create legend using the prepared handles/labels
        try:
            leg = ax.legend(handles, labels, loc=loc, fontsize=fontsize, framealpha=0.9)
        except Exception:
            leg = ax.legend(loc=loc, fontsize=fontsize, framealpha=0.9)
        fig.canvas.draw()
        if renderer is None:
            try:
                renderer = fig.canvas.get_renderer()
            except Exception:
                renderer = None

        try:
            bbox = leg.get_window_extent(renderer=renderer).expanded(1.0 + padding_px/100.0, 1.0 + padding_px/100.0)
        except Exception:
            bbox = None

        overlap = False
        if bbox is not None:
            for (px, py) in pts:
                if bbox.contains(px, py):
                    overlap = True
                    break

        if not overlap:
            return leg
        # remove and try next
        try:
            leg.remove()
        except Exception:
            pass

    # Fallback: place upper right with semi-transparent box
    try:
        return ax.legend(handles, labels, loc='upper right', fontsize=fontsize, framealpha=0.9)
    except Exception:
        return ax.legend(loc='upper right', fontsize=fontsize, framealpha=0.9)



# =============================================================================
# 0. PLOT FORMATTING
# =============================================================================
plt.rcParams.update({
    "font.family":          "serif",
    "font.serif":           ["Times New Roman"],
    "mathtext.fontset":     "cm",
    "axes.labelsize":       11,
    "xtick.labelsize":      10,
    "ytick.labelsize":      10,
    "legend.fontsize":       9,
    "axes.spines.top":      True,
    "axes.spines.right":    True,
    "xtick.direction":      "in",
    "ytick.direction":      "in",
    "xtick.minor.visible":  True,
    "ytick.minor.visible":  True,
})


# =============================================================================
# 1. SALT THERMOPHYSICAL PROPERTIES
# =============================================================================
# Each salt needs: density rho(T), specific heat cp(T), and a reference
# conduction thermal conductivity.
#
# Format:
#   'rho': (a, b) for rho = a + b*T  [kg/m^3, K]      — from MSTDB
#   'cp':  float or (a, b) for cp = a + b*T  [J/kg/K]  — from literature
#   'T_fus': melting temperature [K]
#   'k_conduction_ref': reference conduction conductivity near T_fus [W/m/K]
#   'k_conduction_slope': exponent for T-dependence: k_cond = k_ref + k_ref_slope*T
#   'L_lfa': default LFA sample thickness [m]
#
#   'published_k': list of dicts with published LFA/measurement data
#       Each dict: {'T_K': [...], 'k': [...], 'label': '...', 'marker': '...'}

SALT_CASES: Dict[str, dict] = {
    'FLiNaK': {
        'rho': (2680.0, -0.685),        # MSTDB
        'cp': 1880.0,                    # ~constant, Grimes (1966)
        'T_fus': 735.0,
        'k_conduction_ref': 1.24,           # MSTDB
        'k_conduction_slope': -0.00054,     # MSTDB
        'L_lfa': 0.002,                  # 2 mm default
        'published_k': [
            # Add your own published LFA data here:
            {
                'T_K': [495+273.15, 549+273.15, 599+273.15],
                'k': [2.1e-7*((2680-0.685*(495+273.15))*1880), 2.2e-7*((2680-0.685*(549+273.15))*1880), 2.3e-7*((2680-0.685*(599+273.15))*1880)],
                'label': 'Rose (2020, LFA)',
                'marker': 's', 'color': 'blue',
            },
        ],
    },
    'NaCl': {
        'rho': (2140.0, -0.543),
        'cp': 1080.0,
        'T_fus': 1073.8,
        'k_conduction_ref': 0.712,
        'k_conduction_slope': -0.00018,
        'L_lfa': 0.002,
        'published_k': [
            {
                'T_K': [1169.44, 1171.52, 1274.43, 1294.18, 1354.47, 1392.93, 1403.33, 1401.25, 1440.75, 1438.67],
                'k': [0.51, 0.49, 0.49, 0.47, 0.46, 0.46, 0.46, 0.44, 0.45, 0.42],
                'label': 'Nagasaka (1992, Forced Rayleigh Scattering)',
                'marker': 's', 'color': 'blue',
            }
        ],
    },
'NaCl-KCl': {
        'rho': (2130.0, -0.568),
        'cp': 1060.0,
        'T_fus': 930.8,
        'k_conduction_ref': 0.299,
        'k_conduction_slope': -0.00018,
        'L_lfa': 0.002,
        'published_k': [
            {
                'T_K': [933.4975369, 950.6685433, 971.4989444, 988.9514426, 1009.500352],
                'k': [0.516580311, 0.400222058, 0.524130274, 0.423760178, 0.489489267],
                'label': 'Ruth (2024, Needle Probe)',
                'marker': 's', 'color': 'blue',
            },
        ],
    },
    'NaCl-UCl$_3$': {
        # 63NaCl - 37UCl3 mixture (matching Salt_RHT_Properties.csv 'NaCl-UCl$_3$')
        'rho': (4220.0, -0.00103),
        'cp': 590.0,                    # Rose, 2023
        'T_fus': 829.0,
        'k_conduction_ref': 0.370374732,
        'k_conduction_slope': -0.000131804,
        'L_lfa': 0.002,
        'published_k': [
            # Add your own published LFA data here:
            {
                'T_K': [869.1489361702127,921.1328349626222,971.046578493387,1021.1903392754457,1071.1040828062105],
                'k': [0.26547619047619014,0.3119047619047619,0.341269841269841,0.36984126984126964,0.38134920634920616],
                'label': 'Rose (2023, LFA)',
                'marker': 's', 'color': 'blue',
            },
            {
                'T_K': [808.97, 802, 804, 804, 804, 915.86, 916, 912.69, 912.75, 1020.87, 1021.07, 1021.03, 1021.12],
                'k': [0.27, 0.22, 0.22, 0.22, 0.22, 0.23, 0.24, 0.23, 0.24, 0.17, 0.20, 0.18, 0.18],
                'label': 'Termini (2024, Variable Gap)',
                'marker': 'o', 'color': 'red',
            },
        ],
    },
    'LiF': {
        'rho': (2370.0, -0.50),
        'cp': 2390.0,                    # Janz (1988)
        'T_fus': 1121.2,
        'k_conduction_ref': 1.88,
        'k_conduction_slope': -0.000399,
        'L_lfa': 0.002,
        'published_k': [
            {
                'T_K': [1150.52, 1151.04, 1168.75, 1193.23, 1224.48, 1207.29, 1239.06, 1275.52, 1314.06, 1371.88],
                'k': [1.39, 1.24, 1.34, 1.05, 1.31, 1.45, 1.47, 1.44, 1.18, 1.24],
                'label': 'Golyshev (1992, Concentric Cylinders)',
                'marker': 's', 'color': 'blue',
            }
        ],
    },
}


# =============================================================================
# 2. HELPER FUNCTIONS
# =============================================================================

def load_salt_data(salt_name: str,
                   filename: str = 'Salt_RHT_Properties.csv'
                   ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Load temperature-dependent kappa_P and n_eff from the absorption model CSV.

    Returns
    -------
    T_array     : temperature array [K]
    kappa_array : Planck-mean absorption coefficient [m^-1]
    n_array     : Planck-mean refractive index
    """
    try:
        script_dir = os.path.dirname(os.path.abspath(__file__))
    except NameError:
        script_dir = os.getcwd()
    full_path = os.path.join(script_dir, filename)

    if not os.path.exists(full_path):
        raise FileNotFoundError(
            f"Database not found: {full_path}\n"
            "Run the absorption model first to generate Salt_RHT_Properties.csv.")

    df = pd.read_csv(full_path)
    row = df[df['Salt'] == salt_name]
    if row.empty:
        available = df['Salt'].unique().tolist()
        raise ValueError(
            f"Salt '{salt_name}' not in database. Available: {available}")

    row = row.iloc[0]
    T = np.array([float(x) for x in str(row['Temperature_List_K']).split(',')])
    kappa = np.array([float(x) for x in str(row['Absorption_List_m1']).split(',')])
    n = np.array([float(x) for x in str(row['Refractive_Index_List']).split(',')])

    # Optional spectral arrays (wavelength [um], absorption spectrum, refractive index spectrum)
    wl_um = None
    alpha_spec = None
    n_spec = None
    if 'Wavelength_List_um' in row.index:
        try:
            wl_um = np.array([float(x) for x in str(row['Wavelength_List_um']).split(',')])
        except Exception:
            wl_um = None

    # Attempt to find a matching spectral column for a temperature near the melting point
    if wl_um is not None:
        # look for columns like 'Absorption_Spectrum_T1121K'
        spec_cols = [c for c in row.index if str(c).startswith('Absorption_Spectrum_T')]
        if spec_cols:
            # Find the spectrum column with temperature closest to T_fus (rounded)
            try:
                T_fus = float(row.get('T_fus_K', np.nan))
            except Exception:
                T_fus = np.nan

            best_col = None
            if not np.isnan(T_fus):
                best_diff = 1e9
                for c in spec_cols:
                    try:
                        tstr = c.replace('Absorption_Spectrum_T', '').replace('K', '')
                        tc = float(tstr)
                        diff = abs(tc - T_fus)
                        if diff < best_diff:
                            best_diff = diff
                            best_col = c
                    except Exception:
                        continue
            else:
                best_col = spec_cols[0]

            if best_col is None:
                best_col = spec_cols[0]

            try:
                alpha_spec = np.array([float(x) for x in str(row[best_col]).split(',')])
            except Exception:
                alpha_spec = None

            # corresponding refractive index column name
            n_col = best_col.replace('Absorption_Spectrum', 'Refractive_Index_Spectrum')
            if n_col in row.index:
                try:
                    n_spec = np.array([float(x) for x in str(row[n_col]).split(',')])
                except Exception:
                    n_spec = None

    return T, kappa, n, wl_um, alpha_spec, n_spec


def density_at_T(rho_coeffs: Tuple[float, float], T: float) -> float:
    """Linear density: rho(T) = a + b*T [kg/m^3]."""
    return rho_coeffs[0] + rho_coeffs[1] * T


def cp_at_T(cp_input, T: float) -> float:
    """Specific heat: constant or linear cp(T) = a + b*T [J/kg/K]."""
    if isinstance(cp_input, (int, float)):
        return float(cp_input)
    return cp_input[0] + cp_input[1] * T


def k_conduction(T: float, T_fus: float, k_ref: float, k_ref_B: float) -> float:
    """
    Conduction thermal conductivity (Gheribi et al., 2014):
        k_conduction(T) = k_ref * (T_fus / T)^exponent

    Gives decreasing k with temperature — expected for conduction conduction
    in liquids where increased thermal motion disrupts heat transfer.
    """
    if T <= 0:
        return k_ref
    return k_ref + k_ref_B*T


def k_rad_deissler(T: float, n: float, kappa_P: float, L: float) -> float:
    """
    Deissler bridging radiative conductivity [W/m/K]:

        k_rad = 16 n^2 sigma T^3 / (3 kappa_P + 4/L)

    Smoothly interpolates between:
        - Optically thick (tau >> 1): reduces to Rosseland
        - Optically thin  (tau << 1): radiation across gap ~ L

    Parameters
    ----------
    T       : temperature [K]
    n       : refractive index
    kappa_P : Planck-mean absorption coefficient [m^-1]
    L       : characteristic length (sample thickness) [m]
    """
    if kappa_P <= 0 and L <= 0:
        return 0.0
    denom = 3.0 * kappa_P + (4.0 / L if L > 0 else 0.0)
    if denom <= 0:
        return 0.0
    return 16.0 * n**2 * sigma_SB * T**3 / denom


def k_rad_spectral_deissler(wl_m: np.ndarray, T: float, L: float,
                            alpha_spec: Optional[np.ndarray] = None,
                            n_spec: Optional[np.ndarray] = None,
                            salt_obj=None) -> float:
    """
    Spectrally-resolved Deissler-like radiative conductivity.

    For each wavelength compute the Deissler denominator using the
    spectral absorption coefficient alpha(lambda) and refractive index n(lambda):

        k_rad(lambda) = 16 n(lambda)^2 sigma T^3 / (3 alpha(lambda) + 4/L)

    Then compute the Planck-weighted average:

        k_rad_spectral = integral( k_rad(lambda) * B_lambda(T) d_lambda )
                          / integral( B_lambda(T) d_lambda )

    This preserves spectral variation in alpha and n and is more accurate
    than using scalar Planck-mean kappa and n inside the nonlinear Deissler
    denominator.
    """
    # Compute spectral alpha and n from provided arrays or from the model
    if alpha_spec is None or n_spec is None:
        if salt_obj is None:
            raise ValueError('Either spectral arrays or a salt object must be provided')
        alpha_spec, n_spec = compute_alpha_total(wl_m, T, salt_obj)

    # Avoid zeros in alpha (treat as optically thin where appropriate)
    alpha_safe = np.maximum(alpha_spec, 1e-20)

    # Per-wavelength Deissler conductivity
    denom = 3.0 * alpha_safe + (4.0 / L if L > 0 else 0.0)
    k_rad_lambda = 16.0 * (n_spec ** 2) * sigma_SB * (T ** 3) / denom

    # Weight by Planck function
    B = planck_spectral_radiance(wl_m, T)
    num = np.trapezoid(k_rad_lambda * B, wl_m)
    den = np.trapezoid(B, wl_m)
    return float(num / den) if den > 0 else 0.0


def k_rad_rosseland(T: float, n: float, kappa_P: float) -> float:
    """
    Rosseland (optically thick) radiative conductivity [W/m/K]:

        k_rad = 16 n^2 sigma T^3 / (3 kappa_P)

    Valid only when optical thickness tau = kappa_P * L >> 1.
    """
    if kappa_P <= 0:
        return 0.0
    return 16.0 * n**2 * sigma_SB * T**3 / (3.0 * kappa_P)


# =============================================================================
# 3. CASE STUDY 1: THERMAL CONDUCTIVITY DECOMPOSITION
# =============================================================================

def case_1_conductivity_decomposition(
        T_arr: np.ndarray,
        kappa_arr: np.ndarray,
        n_arr: np.ndarray,
        salt_name: str,
        salt_props: dict,
        output_dir: str) -> plt.Figure:
    """
    Decompose the LFA-measured thermal conductivity into conduction and
    radiative components.

    What this plot shows:
        - k_conduction(T): decreasing with T (Gheribi model)
        - k_rad(T): increasing with T (proportional to T^3 / kappa_P)
        - k_total(T) = k_conduction + k_rad: what LFA actually measures
        - Red shading: the radiative "error" that standard LFA doesn't separate
        - Published LFA data: for comparison with k_total

    Physics insight:
        The conduction part decreases while the radiative part increases with T.
        At some crossover temperature, radiation dominates.  Published LFA
        measurements that show a flat or increasing k(T) may be capturing
        this radiative contribution, not an increase in conduction conduction.
    """
    L = salt_props.get('L_lfa', 0.002)
    T_fus = salt_props['T_fus']

    # Only analyze above melting point
    mask = T_arr >= T_fus
    T = T_arr[mask]
    kappa = kappa_arr[mask]
    n_eff = n_arr[mask]

    if len(T) < 2:
        print(f"  Skipping {salt_name}: not enough data above T_fus={T_fus} K")
        return None

    # Compute components
    k_cond = np.array([k_conduction(Ti, T_fus, salt_props['k_conduction_ref'],
                               salt_props['k_conduction_slope']) for Ti in T])
    k_rd = np.array([k_rad_deissler(Ti, ni, ki, L)
                      for Ti, ni, ki in zip(T, n_eff, kappa)])
    k_total = k_cond + k_rd

    # Optical thickness at midpoint for annotation
    i_mid = len(T) // 2
    tau_mid = kappa[i_mid] * L
    tau_max = kappa[-1] * L

    # Radiative fraction at highest temperature
    rad_frac_max = k_rd[-1] / k_total[-1] * 100 if k_total[-1] > 0 else 0

    # ---- Plot ----
    fig, ax = plt.subplots(figsize=(6, 4.5), constrained_layout=True)

    # Conduction conduction baseline
    ax.plot(T, k_cond, 'b--', linewidth=1.5,
            label='$k_{\\mathrm{cond}}(T)$')

    # Radiative contribution
    ax.plot(T, k_rd, 'r:', linewidth=1.5,
            label='$k_{\\mathrm{rad}}(T)$ (Deissler, '
                  f'L = {L*1e3:.0f} mm)')

    # Total = what LFA measures
    ax.plot(T, k_total, 'k-', linewidth=2.0,
            label='$k_{\\mathrm{total}}$ = $k_{\\mathrm{cond}}$ + '
                  '$k_{\\mathrm{rad}}$')

    # Shading for radiative contribution
    ax.fill_between(T, k_cond, k_total, color='red', alpha=0.12,
                    label=f'Radiative contribution '
                          f'({rad_frac_max:.1f}% at {T[-1]:.0f} K)')

    # Published data overlay
    published = salt_props.get('published_k', [])
    default_markers = ['o', 's', '^', 'v', 'D', '*']
    default_colors = ['green', 'purple', 'orange', 'brown', 'teal', 'gray']
    for i, pub in enumerate(published):
        mk = pub.get('marker', default_markers[i % len(default_markers)])
        # Avoid using blue or red for published-data markers so they don't
        # get confused with the model spectrum lines. Use default palette
        # when authors specified 'blue' or 'red'. Make markers translucent.
        supplied_clr = pub.get('color', None)
        if supplied_clr is None:
            cl = default_colors[i % len(default_colors)]
        else:
            sc = str(supplied_clr).lower()
            if sc in ('blue', 'b', '#0000ff', 'red', 'r', '#ff0000'):
                cl = default_colors[i % len(default_colors)]
            else:
                cl = supplied_clr

        ax.scatter(pub['T_K'], pub['k'], marker=mk, color=cl,
                   s=56, edgecolors='black', linewidth=0.5,
                   zorder=5, alpha=0.65,
                   label=pub.get('label', f'Published {i+1}'))

    # Add summary info into legend instead of as an axes text box so it
    # remains inside the plot but does not overlap datapoints.
    info_label = (f"{salt_name} — L = {L*1e3:.0f} mm, "
                  f"$\\tau$ = {tau_mid:.1f}\u2013{tau_max:.1f}")
    # Create an invisible handle with the info label for the legend
    ax.plot([], [], ' ', label=info_label)

    # Attach the info label to the Figure so callers can access it later
    fig.info_label = info_label

    ax.set_xlabel('Temperature (K)')
    ax.set_ylabel('Thermal Conductivity (W m$^{-1}$ K$^{-1}$)')
     #ax.set_title('Case 1: LFA Thermal Conductivity Decomposition')
    place_legend_avoiding_points(ax, fontsize=9, first_label=info_label)

    pdf_path = os.path.join(output_dir,
                            f'Case1_k_decomposition_{salt_name}.pdf')
    png_path = os.path.join(output_dir,
                            f'Case1_k_decomposition_{salt_name}.png')
    fig.savefig(pdf_path, dpi=1200, bbox_inches='tight')
    fig.savefig(png_path, dpi=1200, bbox_inches='tight')
    print(f"  Saved: {pdf_path} and {png_path}")
    return fig


# =============================================================================
# 4. CASE STUDY 2: SAMPLE THICKNESS SENSITIVITY
# =============================================================================

def case_2_thickness_sensitivity(
        T_arr: np.ndarray,
        kappa_arr: np.ndarray,
        n_arr: np.ndarray,
        salt_name: str,
        salt_props: dict,
        output_dir: str) -> plt.Figure:
    """
    Show how the LFA-measured thermal conductivity depends on sample
    thickness through the optical thickness tau = kappa_P * L.

    What this plot shows:
        - Thinner samples (smaller L) have smaller optical thickness
        - At low tau, more radiation crosses the sample, inflating k_measured
        - At high tau, the sample is effectively opaque and k_rad is small
        - The spread between curves quantifies the LFA thickness artifact

    Physics insight:
        If experimenters use different sample thicknesses and get different
        k values, it's a signature of semi-transparency.  The Deissler
        formula captures this thickness dependence correctly.
    """
    T_fus = salt_props['T_fus']

    mask = T_arr >= T_fus
    T = T_arr[mask]
    kappa = kappa_arr[mask]
    n_eff = n_arr[mask]

    if len(T) < 2:
        print(f"  Skipping {salt_name}: not enough data above T_fus")
        return None

    L_values = [0.001, 0.002, 0.003]  # 1, 2, 3 mm
    colors = ['#e74c3c', '#2ecc71', '#3498db']
    styles = ['-', '--', ':']

    # Conduction baseline (independent of L)
    k_cond = np.array([k_conduction(Ti, T_fus, salt_props['k_conduction_ref'],
                               salt_props['k_conduction_slope']) for Ti in T])

    fig, ax = plt.subplots(figsize=(6, 4.5), constrained_layout=True)

    # Conduction baseline
    ax.plot(T, k_cond, 'k:', linewidth=1.5, alpha=0.7,
            label='$k_{\\mathrm{cond}}$ only')

    # Reference kappa at midpoint for tau annotation
    i_mid = len(T) // 2

    for L, color, ls in zip(L_values, colors, styles):
        k_total = np.empty_like(T)
        for i, (Ti, ni, ki) in enumerate(zip(T, n_eff, kappa)):
            k_r = k_rad_deissler(Ti, ni, ki, L)
            k_total[i] = k_conduction(Ti, T_fus, salt_props['k_conduction_ref'],
                                   salt_props['k_conduction_slope']) + k_r

        tau_mid = kappa[i_mid] * L
        label = (f'L = {L*1e3:.0f} mm '
                 f'($\\tau_{{\\mathrm{{mid}}}}$ = {tau_mid:.1f})')
        ax.plot(T, k_total, color=color, linestyle=ls,
                linewidth=2.0, label=label)

    # Add summary info into the legend rather than an axes text box
    info_label = (f"{salt_name} — $\\kappa_P$ = {kappa[i_mid]:.0f} m$^{{-1}}$ "
                  f"at {T[i_mid]:.0f} K")
    ax.plot([], [], ' ', label=info_label)

    ax.set_xlabel('Temperature (K)')
    ax.set_ylabel('Apparent Thermal Conductivity (W m$^{-1}$ K$^{-1}$)')
     #ax.set_title('Case 2: LFA Sensitivity to Sample Thickness')
    place_legend_avoiding_points(ax, fontsize=9, first_label=info_label)

    pdf_path = os.path.join(output_dir,
                            f'Case2_thickness_{salt_name}.pdf')
    png_path = os.path.join(output_dir,
                            f'Case2_thickness_{salt_name}.png')
    fig.savefig(pdf_path, dpi=1200, bbox_inches='tight')
    fig.savefig(png_path, dpi=1200, bbox_inches='tight')
    print(f"  Saved: {pdf_path} and {png_path}")
    return fig


# =============================================================================
# 5. SUMMARY TABLE
# =============================================================================

def print_summary(T_arr, kappa_arr, n_arr, salt_name, salt_props):
    """Print key metrics at representative temperatures."""
    L = salt_props.get('L_lfa', 0.002)
    T_fus = salt_props['T_fus']
    mask = T_arr >= T_fus
    T, kappa, n_eff = T_arr[mask], kappa_arr[mask], n_arr[mask]

    if len(T) < 2:
        return

    n_pts = min(8, len(T))
    indices = np.linspace(0, len(T) - 1, n_pts, dtype=int)

    print(f"\n  {'T [K]':>7}  {'kP [m-1]':>10}  {'tau':>7}  "
          f"{'k_cond':>7}  {'k_rad':>7}  {'k_tot':>7}  {'rad%':>6}")
    print(f"  {'-'*7}  {'-'*10}  {'-'*7}  "
          f"{'-'*7}  {'-'*7}  {'-'*7}  {'-'*6}")

    for idx in indices:
        Ti, ki, ni = T[idx], kappa[idx], n_eff[idx]
        tau = ki * L
        k_cond = k_conduction(Ti, T_fus, salt_props['k_conduction_ref'],
                         salt_props['k_conduction_slope'])
        k_rd = k_rad_deissler(Ti, ni, ki, L)
        k_tot = k_cond + k_rd
        frac = k_rd / k_tot * 100 if k_tot > 0 else 0

        print(f"  {Ti:>7.0f}  {ki:>10.1f}  {tau:>7.2f}  "
              f"{k_cond:>7.3f}  {k_rd:>7.3f}  {k_tot:>7.3f}  {frac:>6.1f}")
    print()


# =============================================================================
# 6. MAIN
# =============================================================================

if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    figs_dir = os.path.join(script_dir, 'Figures')
    os.makedirs(figs_dir, exist_ok=True)

    # ---- Select salts to analyze ----
    SALTS_TO_ANALYZE = ['FLiNaK', 'NaCl', 'LiF', 'NaCl-UCl$_3$', 'NaCl-KCl']

    for salt_name in SALTS_TO_ANALYZE:
        print(f"\n{'='*60}")
        print(f"  LFA Case Studies: {salt_name}")
        print(f"{'='*60}")

        if salt_name not in SALT_CASES:
            print(f"  No config for {salt_name}. Skipping.")
            continue

        props = SALT_CASES[salt_name]
        try:
            T_arr, kappa_arr, n_arr, wl_um, alpha_spec, n_spec = load_salt_data(salt_name)
        except (FileNotFoundError, ValueError) as e:
            print(f"  Error: {e}")
            continue
        print_summary(T_arr, kappa_arr, n_arr, salt_name, props)

        print("  Case 1: Conductivity decomposition...")
        fig1 = case_1_conductivity_decomposition(
            T_arr, kappa_arr, n_arr, salt_name, props, figs_dir)

        # If spectral arrays were present, compute and overplot spectral Deissler
        if wl_um is not None and alpha_spec is not None and n_spec is not None and fig1 is not None:
            try:
                wl_m = wl_um * 1e-6
                # Representative temperature: midpoint above T_fus used in the plot
                mask = T_arr >= props['T_fus']
                T_above = T_arr[mask]
                if len(T_above) > 0:
                    T_mid = float(T_above[len(T_above) // 2])
                    L = props.get('L_lfa', 0.002)
                    k_rad_spec = k_rad_spectral_deissler(wl_m, T_mid, L,
                                                         alpha_spec=alpha_spec,
                                                         n_spec=n_spec)
                    # annotate saved figure by adding a text note
                    ax = fig1.axes[0]
                    # ax.plot([], [], ' ', label=f'Spectral Deissler $k_{{rad}}$ = {k_rad_spec:.3f} W/mK at {T_mid:.0f} K')
                    place_legend_avoiding_points(ax, fontsize=9, first_label=getattr(fig1, 'info_label', None))
                    fig1.savefig(os.path.join(figs_dir, f'Case1_k_decomposition_{salt_name}_spectral.pdf'), dpi=1200, bbox_inches='tight')
                    fig1.savefig(os.path.join(figs_dir, f'Case1_k_decomposition_{salt_name}_spectral.png'), dpi=1200, bbox_inches='tight')
                    print(f"  Saved spectral comparison: {os.path.join(figs_dir, f'Case1_k_decomposition_{salt_name}_spectral.pdf')}")
            except Exception as e:
                print(f"  Spectral Deissler failed: {e}")

        print("  Case 2: Thickness sensitivity...")
        case_2_thickness_sensitivity(
            T_arr, kappa_arr, n_arr, salt_name, props, figs_dir)

    plt.show()
    print("\nDone. Figures saved to ./Figures/")
